name: CI RSpec Tests

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      bdd-dir: ./bdd

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run bundle install
        working-directory: ${{env.bdd-dir}}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build and test with rspec
        working-directory: ${{env.bdd-dir}}
        run: bundle exec rspec spec
